/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jdk.errorprone;

public class Library {
    public boolean someLibraryMethod() {
        int[] myArray = { 1, 2, 3, 4, 5};
        System.out.println(myArray.toString());
        return true;
    }
}
